/** Downloads generated bytes as a file without round-tripping through a server. */
export function downloadBytes(data: ArrayBuffer | Uint8Array, fileName: string, mime = 'application/pdf'): void {
  const buffer = data instanceof Uint8Array ? data : new Uint8Array(data);
  const blob = new Blob([buffer as BlobPart], { type: mime });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = fileName;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  // Give the browser a tick to start the download before revoking.
  setTimeout(() => URL.revokeObjectURL(url), 10_000);
}

export function downloadBlob(blob: Blob, fileName: string): void {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = fileName;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  setTimeout(() => URL.revokeObjectURL(url), 10_000);
}

export function blobFromBuffer(data: ArrayBuffer, mime: string): Blob {
  return new Blob([data as BlobPart], { type: mime });
}